global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090

  - job_name: http-sd-scrap
    scrape_interval: 15s
    http_sd_configs:
    - url: http://172.22.0.1:9990/targets
  
  - job_name: kafka
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:8000']

  - job_name: pushgateway
    honor_labels: true
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
    - targets: 
      - pushgateway:9091

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['localhost:9093']

